### Creates a New Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "lohith puvvala",
    "email": "lohith@example.com",
    "address": "6-66/1-202, gollapudi, vijayawada, 521225",
    "dateOfBirth": "2002-02-19",
    "registeredDate": "2026-04-25"
}

###